project: sidecar-proxy
repository: https://github.com/d2jvkpn/sidecar-proxy
version: 0.1.0

config: |
  sidecar_proxy:
    service: http://localhost:8000
    cors: "*"
    pass_with_prefix: ["GET@/target"]
    tls: false
    cert: "configs/server.cert"
    key: "configs/server.key"
    basic_auth:
      enable: true
      # enum: md5(username:password), bcrypt
      method: bcrypt
      users:
      - { username: 'hello', password: '$2a$10$scqefoWP3SwzgB.bLkbQ0e0Cre45AA16ibI3lxichOp3FohzQm9BK' }
      # method: md5
      # users:
      # - { username: 'hello', password: '6de41d334b7ce946682da48776a10bb9' }
